version: "3"

services:
  firefox:
    image: selenium/standalone-firefox-debug:3.14.0-curium

    ports:
      - "4444:4444"
      - "5900:5900"

    volumes:
      - "/dev/shm:/dev/shm"

    networks:
      - selenium

  wp-worker:
    dns:
      - 8.8.8.8

    image: meetings-channel
    command: python -u main.py --whatsapp

    environment:
      - SELENIUM=http://firefox:4444/wd/hub

    deploy:
      restart_policy:
        condition: on-failure

    volumes:
      - .:/app
      - ./qrs:/tmp
    networks:
      - selenium
    depends_on:
      - firefox

  mail-worker:
    dns:
      - 8.8.8.8

    image: meetings-channel
    command: python -u main.py --mail

    deploy:
      restart_policy:
        condition: on-failure

volumes:
  devshm:

networks:
  selenium: